project_id = "jajfuajmkjulujnwfqen"

[functions.setup-super-admin]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.generate-marketing-image]
verify_jwt = true

[functions.paystack-payment]
verify_jwt = false

[functions.calculate-distance]
verify_jwt = true

[functions.purchase-tokens]
verify_jwt = false

[functions.orange-money-payment]
verify_jwt = false

[functions.expire-bookings]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.phone-auth]
verify_jwt = false
